######################################
## Vistio-api config
##  Global level - displays traffic from the internet to the istio ingress gateway
##  Cluster level - displays traffic within the istio mesh
######################################
vistioConfig:
  graphName: Vistio
  globalLevel:
    maxVolume: 2000000
    clusterConnections:
      # Total requests per second coming into the ingress controller from internet
      - query: sun(rate(istio_request_count{destination_service="istio-ingressgateway.istio-system.svc.cluster.local"}[1m])) by (response_code)
        prometheusURL: http://prometheus.istio-system
        source:
          replacement: INTERNET
        target:
          replacement: istio-mesh
        status:
          label: response_code
          # color coding of requests
          warningRegex: ^4..$
          dangerRegex: ^5..$
  clusterLevel:
    # Cluster name must match 'target' name in global
    - cluster: istio-mesh
      maxVolume: 3000
      serviceConnections:
        - query: sum(rate(istio_request_count[1m])) by (source_service,destination_service,response_code)
          prometheusURL: http://prometheus.istio-system
          source:
            label: source_service
          target:
            label: destination_service
          status:
            label: response_code
            # color coding of requests
            warningRegex: ^4..$
            dangerRegex: ^5..$
          notices:
            - name: HighErrorRate
              title: "[{{ .value }}] High Error Rate"
              statusType: danger
              severityThreshold:
                # Warning alert at 1%
                warning: .01
                # Error alert at 5%
                error: .05